Fail test

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,7 +1,7 @@
 #!/bin/bash
 echo "Running tests..."
 echo "Pass"
-sleep 1m
-exit 0
-# echo "Fail"
-# exit 1
+#sleep 1m
+#exit 0
+echo "Fail"
+exit 1
